- job:
    name: taskflow-functional
    parent: openstack-tox
    abstract: true
    pre-run: playbooks/tests/functional/pre.yml
    vars:
      tox_envlist: functional
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^LICENSE$
      - ^releasenotes/.*$
      - ^\.pre-commit-config\.yaml$

- job:
    name: taskflow-functional-redis
    parent: taskflow-functional
    vars:
      tox_environment:
        PIFPAF_DAEMON: redis

- job:
    name: taskflow-functional-etcd
    parent: taskflow-functional
    vars:
      tox_environment:
        PIFPAF_DAEMON: etcd
        SETUP_ENV_SCRIPT: ./setup-etcd-env.sh

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-python3-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-docs:
            nodeset: ubuntu-jammy
        - taskflow-functional-redis
        - taskflow-functional-etcd
    gate:
      jobs:
        - openstack-tox-docs:
            nodeset: ubuntu-jammy
        - taskflow-functional-redis
        - taskflow-functional-etcd
