- project:
    templates:
      - check-requirements
      - lib-forward-testing
      - lib-forward-testing-python3
      - openstack-lower-constraints-jobs
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
