- job:
    name: taskflow-functional
    parent: openstack-tox
    abstract: true
    pre-run: playbooks/tests/functional/pre.yml
    vars:
      tox_envlist: functional

- job:
    name: taskflow-functional-redis
    parent: taskflow-functional
    vars:
      tox_environment:
        PIFPAF_DAEMON: redis

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-python3-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - taskflow-functional-redis
    gate:
      jobs:
        - taskflow-functional-redis
