# Temporary job until SQLAlchemy 2.0 is no longer blocked by upper-requirements
- job:
    name: taskflow-tox-py310-with-sqlalchemy-2x
    parent: openstack-tox-py310
    description: |
      Run unit tests with main branch of SQLAlchemy, alembic and oslo.db.
      Takes advantage of the base tox job's install-siblings feature.
    # The job only tests the latest and shouldn't be run on the stable branches
    branches:
      regex: ^stable/.*$
      negate: true
    required-projects:
      - name: github.com/sqlalchemy/sqlalchemy
        override-checkout: main
      - name: github.com/sqlalchemy/alembic
        override-checkout: main
      - name: openstack/oslo.db

- job:
    name: taskflow-functional
    parent: openstack-tox
    abstract: true
    pre-run: playbooks/tests/functional/pre.yml
    vars:
      tox_envlist: functional

- job:
    name: taskflow-functional-redis
    parent: taskflow-functional
    vars:
      tox_environment:
        PIFPAF_DAEMON: redis

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-python3-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - taskflow-tox-py310-with-sqlalchemy-2x
        - taskflow-functional-redis
    gate:
      jobs:
        - taskflow-tox-py310-with-sqlalchemy-2x
        - taskflow-functional-redis
